// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xinslkxcxntaertkzmwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpbnNsa3hjeG50YWVydGt6bXdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0ODY2MjQsImV4cCI6MjA4NTA2MjYyNH0.imAJ_7wldjPKM1I2ZI43j0neQ9VxV9gSZCt71M7ZI18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
